spring:
  application:
    name: FinanceTicker

server:
  port: 8080

environment:

#create a section somehow for tagging api keys and write into the.env file or global values/filepaths
#finance-ticker.api-keys.*, cors.allowed-origins