spring:
  application:
    name: FinanceTicker

server:
  port: 8080

finance-ticker:
  api-keys:
    finnhub: ${FINANCE_TICKER_API_KEYS_FINNHUB:-}
    coingecko: ${FINANCE_TICKER_API_KEYS_COINGECKO:-}
    exchangerate: ${FINANCE_TICKER_API_KEYS_EXCHANGERATE:-}

cors:
  allowed-origins: "*"